@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftcomesalive.mca.client.renderer.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;