@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftcomesalive.mca.entity.villager;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;