@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftcomesalive.mca.entity.player;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;