@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftcomesalive.mca.entity.merchant;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;