@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minecraftcomesalive.mca.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;